[user_info]
api_key = "your_api_key"

[program_config]
interval = 1

[devices]
huawei_nexus_6p = "uf34031sdas"
"Huawei Nexus 6P" = "do"

[subreddits]
mechmarket = ["Planck", "Dog", "Man"]
gamedeals = ["Batman", "Battlefield"]