[subreddits]
mechmarket = ["Planck"]
gamedeals = ["Battlefield"]
programming = ["Rust"]

[devices]
huawei_nexus_6p = "ujAoL3MXhg4sjz3yaXuUnY"

[program_config]
interval = ".2"

[user_info]
token = "o.KxfuUTq4hC6a26wlxFyCjSEpSKiVLzbr"

[last_result]
programming_rust = "https://www.reddit.com/r/programming/comments/8lms0w/resvg_03_an_svg_rendering_library_rrust/"
mechmarket_planck = "https://www.reddit.com/r/mechmarket/comments/8m9q5s/eudeh_paypal_w_wooden_wrist_rest_for_planckcontra/"
gamedeals_battlefield = "https://www.reddit.com/r/GameDeals/comments/8lagoh/origin_battlefield_1_in_the_name_of_the_tsar_dlc/"

