[user_info]
api_key = "your_api_key"

[program_config]
interval = 2

[devices]
huawei_nexus_6p = "uf34031sdas"

[subreddits]
mechmarket = ["Planck", "Dog", "Man"]
gamedeals = ["Batman", "Battlefield"]